export const ERROR_CODES = {
  VALIDATION_ERROR: "E001",
  NOT_FOUND: "E002",
  DATABASE_FAILURE: "E003",
  INTERNAL_ERROR: "E500",
  UNAUTHORIZED: "E401",
  FORBIDDEN: "E403",
  CONFLICT: "E409",
  RATE_LIMIT_EXCEEDED: "E429",
  USER_FETCH_ERROR: "E101",
  USER_CREATION_FAILED: "E102",
  USER_UPDATE_FAILED: "E103",
  USER_DELETION_FAILED: "E104",
  TASK_CREATION_FAILED: "E201",
  TASK_FETCH_ERROR: "E202",
  TASK_UPDATE_FAILED: "E203",
  TASK_DELETION_FAILED: "E204",
} as const;

export type ErrorCodeType = typeof ERROR_CODES[keyof typeof ERROR_CODES];
